In [1]:
import pandas as pd

In [3]:
# From dictionary
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

# From list of lists
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])
df

    Name  Age
0  Alice   25
1    Bob   30

In [4]:
df.head()
df.tail()
df.info()
df.describe()
df

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df['Name']
df[['Name', 'Age']]

df.loc[0]
df.iloc[1]
df

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [7]:
df['Gender'] = ['F', 'M']
df.drop('Age', axis=1, inplace=True)
df

    Name Gender
0  Alice      F
1    Bob      M

In [10]:
data = {
    'Name': ['Alice', 'Bob'],
    'Age': [25, 30],
    'Gender': ['F', 'M']
}

df = pd.DataFrame(data)
df.groupby('Gender')['Age'].mean()
df

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [12]:
df1 = pd.DataFrame({'key': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'key': [1, 2], 'Age': [25, 30]})

pd.merge(df1, df2, on='key')

   key   Name  Age
0    1  Alice   25
1    2    Bob   30

In [14]:
df = pd.read_csv('data.csv')
df.to_csv('output.csv', index=False)
df

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [15]:
df.sort_values('Age')
df['Age'].apply(lambda x: x + 1)
df['Name'].unique()
df['Age'].value_counts()
df

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M